export const programs = new Map([
  ['common.export-page', '../skills/common/export-page.mjs'],
  ['common.download-resource', '../skills/common/download-resource.mjs'],
  ['common.collect-links', '../skills/common/collect-links.mjs'],
  ['common.collect-table', '../skills/common/collect-table.mjs'],
  ['common.multi-tab-compare', '../skills/common/multi-tab-compare.mjs'],
  ['common.batch-form-fill', '../skills/common/batch-form-fill.mjs'],
  ['common.search-pagination', '../skills/common/search-pagination.mjs'],
  ['github.resolve-context', '../skills/github/resolve-context.mjs'],
  ['github.acquire-repository', '../skills/github/acquire-repository.mjs'],
  ['github.acquire-file', '../skills/github/acquire-file.mjs'],
  ['github.acquire-directory', '../skills/github/acquire-directory.mjs'],
  ['github.inspect-pr', '../skills/github/inspect-pr.mjs'],
  ['github.inspect-failed-actions-run', '../skills/github/inspect-failed-actions-run.mjs'],
  ['github.compare-refs', '../skills/github/compare-refs.mjs'],
  ['github.collect-repository-summary', '../skills/github/collect-repository-summary.mjs'],
  ['developer.collect-debug-summary', '../skills/developer/collect-debug-summary.mjs'],
  ['developer.investigate-console-error', '../skills/developer/investigate-console-error.mjs'],
  ['developer.capture-performance-profile', '../skills/developer/capture-performance-profile.mjs'],
  ['developer.analyze-memory-leak', '../skills/developer/analyze-memory-leak.mjs'],
  ['developer.audit-agent-readiness', '../skills/developer/audit-agent-readiness.mjs'],
  ['developer.inspect-webmcp', '../skills/developer/inspect-webmcp.mjs'],
  ['developer.inspect-runtime-tools', '../skills/developer/inspect-runtime-tools.mjs'],
  ['developer.lighthouse-audit', '../skills/developer/lighthouse-audit.mjs']
]);
